
package proxyY;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://WebSerbvices.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://WebSerbvices.com/", className = "proxyY.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://WebSerbvices.com/", className = "proxyY.ConversionResponse")
    @Action(input = "http://WebSerbvices.com/BanqueWS/conversionRequest", output = "http://WebSerbvices.com/BanqueWS/conversionResponse")
    public double conversion(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxyY.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WebSerbvices.com/", className = "proxyY.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WebSerbvices.com/", className = "proxyY.GetCompteResponse")
    @Action(input = "http://WebSerbvices.com/BanqueWS/getCompteRequest", output = "http://WebSerbvices.com/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
