
package proxyY;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BanqueWSService", targetNamespace = "http://WebSerbvices.com/", wsdlLocation = "http://localhost:9090/BanqueWS?wsdl")
public class BanqueWSService
    extends Service
{

    private final static URL BANQUEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANQUEWSSERVICE_EXCEPTION;
    private final static QName BANQUEWSSERVICE_QNAME = new QName("http://WebSerbvices.com/", "BanqueWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/BanqueWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUEWSSERVICE_WSDL_LOCATION = url;
        BANQUEWSSERVICE_EXCEPTION = e;
    }

    public BanqueWSService() {
        super(__getWsdlLocation(), BANQUEWSSERVICE_QNAME);
    }

    public BanqueWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUEWSSERVICE_QNAME, features);
    }

    public BanqueWSService(URL wsdlLocation) {
        super(wsdlLocation, BANQUEWSSERVICE_QNAME);
    }

    public BanqueWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUEWSSERVICE_QNAME, features);
    }

    public BanqueWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueWS
     */
    @WebEndpoint(name = "BanqueWSPort")
    public BanqueWS getBanqueWSPort() {
        return super.getPort(new QName("http://WebSerbvices.com/", "BanqueWSPort"), BanqueWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueWS
     */
    @WebEndpoint(name = "BanqueWSPort")
    public BanqueWS getBanqueWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebSerbvices.com/", "BanqueWSPort"), BanqueWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUEWSSERVICE_EXCEPTION!= null) {
            throw BANQUEWSSERVICE_EXCEPTION;
        }
        return BANQUEWSSERVICE_WSDL_LOCATION;
    }

}
